alex:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 5

    # Position Controllers ---------------------------------------
    pan_mechanism_joint_controller:
      type: position_controllers/JointPositionController
      joint: pan_mechanism_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}

    tilt_mechanism_joint_controller:
      type: position_controllers/JointPositionController
      joint: tilt_mechanism_joint
      pid: { p: 1.0, i: 1.0, d: 0.0 }
    # To add more just add them here as the first one