wheel_base: 0.1725
wheel_diameter: 0.074
right_motor_port: "M1"
right_motor_forward_direction: "CCW"
left_motor_port: "M4"
left_motor_forward_direction: "CW"
servo_port_1: "S1"
servo_port_1_define: "pan"
tilt_servo_port: "S4"
servo_port_2_define: "tilt"
