<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="alex">

    <material name="grey">
        <color rgba="0.75 0.75 0.75 0.5"/>
    </material>

    <material name="red">
        <color rgba="0.8 0 0 1"/>
    </material>

    <material name="black">
        <color rgba="0.8 0.8 0.8 1"/>
    </material>

    <material name="pi-top_green">
        <color rgba="0 0.7 0.64 1"/>
    </material>



    <!-- Chassis Properties -->
    <xacro:property name="chassis_mass" value="0.1"/>
    <xacro:property name="chassis_width_x" value="0.192"/>
    <xacro:property name="chassis_depth_y" value="0.059"/>
    <xacro:property name="chassis_height_z" value="0.276"/>
    <xacro:property name="chassis_ixx" value="${(chassis_mass / 12.0) * (chassis_depth_y**2 + chassis_height_z**2)}"/>
    <xacro:property name="chassis_iyy" value="${(chassis_mass / 12.0) * (chassis_width_x**2 + chassis_height_z**2)}"/>
    <xacro:property name="chassis_izz" value="${(chassis_mass / 12.0) * (chassis_width_x**2 + chassis_depth_y**2)}"/>

    <xacro:macro name="chassis_origin">
        <origin xyz="0 ${-chassis_depth_y/2} 0" rpy="0 0 0"/>
    </xacro:macro>

    <xacro:macro name="chassis_joint_origin">
        <origin xyz="-0.068 0 0.056475" rpy="${pi/2} 0 ${-pi/2}"/>
    </xacro:macro>
    <!-- * * * * * * * * * -->

    <!-- Wheel Properties -->
    <xacro:property name="wheel_mass" value="0.01"/>
    <xacro:property name="wheel_width" value="0.029"/>
    <xacro:property name="wheel_radius" value="0.0375"/>
    <xacro:property name="wheel_ixx" value="${(wheel_mass / 12.0) * (3 * wheel_radius**2 + wheel_width**2)}"/>
    <xacro:property name="wheel_iyy" value="${wheel_ixx}"/>
    <xacro:property name="wheel_izz" value="${(chassis_mass * wheel_radius**2) / 2}"/>

    <xacro:macro name="right_wheel_joint_origin">
        <origin xyz="0 -0.0805 0" rpy="${-pi/2} 0 0"/>
    </xacro:macro>

    <xacro:macro name="left_wheel_joint_origin">
        <origin xyz="0 0.0805 0" rpy="${pi/2} 0 0"/>
    </xacro:macro>
    <!-- * * * * * * * * * -->

    <!-- Macros -->
    <xacro:macro name="x_axis">
        <axis xyz="1 0 0"/>
    </xacro:macro>

    <xacro:macro name="y_axis">
        <axis xyz="0 1 0"/>
    </xacro:macro>

    <xacro:macro name="z_axis">
        <axis xyz="0 0 1"/>
    </xacro:macro>

    <!-- * * * * * * * * * -->

    <!-- Model Definitions -->

    <link name="base_link">
        <pose>0 0 ${wheel_radius} 0 0 0</pose>
        <visual>
            <origin rpy="0.0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
            <material name="red"/>
        </visual>
    </link>


    <link name="chassis">
        <inertial>
            <xacro:chassis_origin/>
            <mass value="${chassis_mass}"/>
            <inertia ixx="${chassis_ixx}" ixy="0.0" ixz="0.0" iyy="${chassis_iyy}" iyz="0.0" izz="${chassis_izz}"/>
        </inertial>
        <visual>
            <xacro:chassis_origin/>
            <geometry>
                <box size="${chassis_width_x} ${chassis_depth_y} ${chassis_height_z}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <xacro:chassis_origin/>
            <geometry>
                <box size="${chassis_width_x} ${chassis_depth_y} ${chassis_height_z}"/>
            </geometry>
        </collision>
    </link>

    <joint name="baselink_chassis_joint" type="fixed">
    	<parent link="base_link"/>
    	<child link="chassis"/>
    	<xacro:chassis_joint_origin/>
	</joint>

    <link name="right_wheel">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${wheel_ixx}" ixy="0.0" ixz="0.0" iyy="${wheel_iyy}" iyz="0.0" izz="${wheel_izz}"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
    </link>

    <joint name="baselink_right_wheel_joint" type="continuous">
    	<parent link="base_link"/>
    	<child link="right_wheel"/>
    	<xacro:right_wheel_joint_origin/>
        <limit effort="1.0" velocity="0.45"/>
        <xacro:z_axis/>
	</joint>

    <link name="left_wheel">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${wheel_ixx}" ixy="0.0" ixz="0.0" iyy="${wheel_iyy}" iyz="0.0" izz="${wheel_izz}"/>
        </inertial>
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
        </collision>
    </link>

    <joint name="baselink_left_wheel_joint" type="continuous">
    	<parent link="base_link"/>
    	<child link="left_wheel"/>
    	<xacro:left_wheel_joint_origin/>
        <limit effort="1.0" velocity="0.45"/>
        <xacro:z_axis/>
	</joint>

    <!--<link name="castor_swivel">

    </link>

    <link name="castor_wheel">

    </link>

    <link name="chassis">

    </link>-->


</robot>